Hw11
gvsem/formal-lang-course pull request #10
Opened 2024-05-17 15:58 UTC by gvsem

2024-05-17 16:22 UTC, WoWaster requested changes

2024-05-17 17:05 UTC, gvsem commented on project/lang.py
> +        pass
Исправил на один стиль с visitor

2024-05-17 17:30 UTC, WoWaster commented
А с генерацией всё так же проблемы?

2024-05-17 17:33 UTC, gvsem commented
> А с генерацией всё так же проблемы?

Да, ничего не поменялось. Важно, чтобы были и подчеркивания, и кавычка в VAR, иначе он иногда падает на 2-6 примерах из корректных 100 штук.

2024-05-21 09:10 UTC, WoWaster commented
Меня удивляет, что у меня никаких проблем с генерацией нет. Можете попросить кого-нибудь проверить с оригинальной грамматикой?

2024-05-21 12:41 UTC, gvsem commented
> Меня удивляет, что у меня никаких проблем с генерацией нет. Можете попросить кого-нибудь проверить с оригинальной грамматикой?

Я пока не могу попросить, поскольку никто не делал. Но я загрузил с оригинальной грамматикой на CI/CD, тут повалились тесты, и вот скриншот, который показывает, что токен содержит подчеркивание

<img width="1049" alt="image" src="https://github.com/gvsem/formal-lang-course/assets/7927563/f9305920-03b0-4c4a-b0b5-a147958664f8">

2024-05-21 13:15 UTC, WoWaster commented
Я нашел дебильный косяк с нашей стороны. Проверяйте

2024-05-21 13:35 UTC, WoWaster commented
У гитхаба видимо шарики за ролики. У меня вроде починилось. У вас тоже?

2024-05-21 13:36 UTC, gvsem commented
> У гитхаба видимо шарики за ролики и CI висит, хотя и прошел. У меня вроде починилось. У вас тоже?

Ага, локально прошло :)

2024-05-21 13:37 UTC, WoWaster approved these changes
Разобрались. Засчитано. Вольёте всё в main, чтобы не висело шесть ПР?

2024-05-21 13:38 UTC, gvsem commented
> Разобрались. Засчитано. Вольёте всё в main, чтобы не висело шесть ПР?

Да, все волью в ближайшее время. Спасибо

2024-05-22 21:02 UTC, merged