Hw5
gvsem/formal-lang-course pull request #5
Opened 2024-03-20 20:06 UTC by gvsem

2024-03-20 21:26 UTC, gvsem commented
добавил файл в репозиторий, назначив assignee

2024-03-26 11:25 UTC, WoWaster requested changes
Много комментариев оставил в Коллабе. Классно, что вы решились сделать эту задачку, надеюсь мы её-таки примем! Но на BFS пристально посмотрите, пожалуйста.

2024-04-11 08:32 UTC, gvsem commented
> Много комментариев оставил в Коллабе. Классно, что вы решились сделать эту задачку, надеюсь мы её-таки примем! Но на BFS пристально посмотрите, пожалуйста.

Внес исправления, в т.ч. изменил алгоритм (2), точно стало лучше, но будто бы все равно медленно

2024-04-18 13:08 UTC, gsvgit commented
Вот теперь почти похоже на правду. BFS действительно требует аккуратности, чтобы сделать его прям быстрым. Хорошо, что теперь сравнимо. Но всё равно один комментарий остался (в колабе повешен): если я правильно понимаю графики, у Вас получилось отрицательное время, что выглядит очень странно. Понятно, что это про интервалы и неподконтрольность окружения, но может как-то обработать выборку, чтобы совсем уж стрёмных графиков не получалось? Выбросы, там, убрать.

2024-05-17 16:16 UTC, gvsem commented
> если я правильно понимаю графики, у Вас получилось отрицательное время, что выглядит очень странно.

Прошу прощения за долгий ответ. Это не усы, а доверительный интервал (т.е. на графиках показано среднее время, а черными линиями – доверительный интервал). Сами значения положительные, но на некоторых измерениях он получается неадекватно большим (пытался перезамерять отдельные графики, но везде все равно какие-нибудь громадные получаются).

2024-05-21 09:23 UTC, WoWaster approved these changes
Такие доверительные интервалы, конечно, мрак, но за старания и понимание засчитываем! 

Отформатируйте код, чтобы CI не орал и вливайте

2024-05-22 20:53 UTC, gvsem commented
CI/CD не проходит, потому что в дальнейшем поменялись тесты на task3. Фиксы были выше по истории гита. Чтобы не мерджить ветки, солью все вместе, все тесты пройдут в main

2024-05-22 20:54 UTC, merged